import copy
import time

import aiofiles

from .image import tricolor_gradient
from .maimaidx_best_50 import *
from .maimaidx_music import Music, mai
from .maimaidx_theme import pic


async def update_rating_table() -> str:
    """更新定数表"""
    try:
        ratingdir.mkdir(parents=True, exist_ok=True)
        from .maimaidx_theme import Theme, resolve_theme_path
        _theme = Theme.get_default().value
        dx = Image.open(resolve_theme_path(maimaidir, _theme, 'DX.png')).convert('RGBA').resize((44, 16))
        diff = [Image.new('RGBA', (75, 16), color) for color in ScoreBaseImage.bg_color]
        sbi = ScoreBaseImage if maiconfig.saveinmem else ScoreBaseImage()
        atime = 0
        for lv in levelList[6:]:
            _otime = time.time()
            picname = ratingdir / f'{lv}.png'
            lvlist = mai.total_level_data[lv]
            lines = 0
            for _lv in lvlist:
                musicnum = len(lvlist[_lv])
                if musicnum == 0:
                    r = 1
                else:
                    remainder = musicnum % 14
                    r = (musicnum // 14) + (1 if remainder else 0)
                lines += r

            if '+' in lv:
                f = 4
            elif lv == '6':
                f = 10
            else:
                f = 6

            linesheight = 85 * lines
            """
            `85` 为曲绘高度 `80` + 间隔 `5`
            `lines` 为行数
            """
            
            width, height = 1400, 325 + f * 20 + linesheight
            """
            `325` 为顶部文字和底部图片高度 + 上下间隔高度
            `f * 20` 为等级数量 `f` * 等级间隔 `20`
            `linesheight` 为各等级曲绘和间隔总和高度
            """
            
            im = tricolor_gradient(width, height)
            
            im.alpha_composite(sbi.aurora_bg)
            im.alpha_composite(sbi.shines_bg, (34, 0))
            im.alpha_composite(sbi.rainbow_bg, (319, height - 643))
            im.alpha_composite(sbi.rainbow_bottom_bg, (100, height - 343))
            for h in range((height // 358) + 1):
                im.alpha_composite(sbi.pattern_bg, (0, (358 + 7) * h))

            dr = ImageDraw.Draw(im)
            sy = DrawText(dr, SIYUAN)
            ts = DrawText(dr, TBFONT)
            _design = resolve_theme_path(maimaidir, _theme, 'design.png')
            if _design.exists():
                im.alpha_composite(Image.open(_design), (200, height - 113))
            sy.draw(
                700, 
                height - 70, 
                22, 
                f'Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {maiconfig.botName} BOT', 
                sbi.text_color, 
                'mm'
            )
            y = 100
            for _lv in lvlist: 
                x = 160
                y += 20
                _chara_lv = resolve_theme_path(maimaidir, _theme, 'UI_CMN_Chara_Level_S_01.png')
                if _chara_lv.exists():
                    im.alpha_composite(
                        Image.open(_chara_lv).resize((80, 80)), (50, y + 80)
                    )
                ts.draw(88, y + 120, 35, _lv, anchor='mm')
                for num, music in enumerate(lvlist[_lv]):
                    if num % 14 == 0:
                        x = 160
                        y += 85
                    else:
                        x += 85
                    cover = Image.open(music_picture(music.id)).resize((75, 75))
                    im.alpha_composite(cover, (x, y))
                    if music.type == 'DX':  # 谱面类型 DX=DX谱面
                        im.alpha_composite(dx, (x + 31, y))
                    im.alpha_composite(diff[int(music.lv)], (x, y + 59))
                    ts.draw(x + 37, y + 67, 13, music.id, sbi.t_color[int(music.lv)], 'mm')
                if not lvlist[_lv]:
                    y += 85

            by = BytesIO()
            im.save(by, 'PNG')
            async with aiofiles.open(picname, 'wb') as f:
                await f.write(by.getbuffer())
            _ntime = int(time.time() - _otime)
            atime += _ntime
            log.info(f'lv.{lv} 定数表更新完成，耗时：{_ntime}s')
        log.info(f'定数表更新完成，共耗时{atime}s')
        return f'定数表更新完成，共耗时{atime}s'
    except Exception as e:
        log.error(traceback.format_exc())
        return f'定数表更新失败，Error: {e}'


async def update_wu_plate_table() -> str:
    """更新舞/霸者完成表（分页）"""
    try:
        plate_tabledir.mkdir(parents=True, exist_ok=True)
        
        # 获取舞的曲目列表
        music_id_list = mai.total_plate_id_list.get('舞')
        if not music_id_list:
            return '未找到舞的牌子数据'
        
        remaster_id_list = mai.total_plate_id_list.get('舞ReMASTER', [])
        music = mai.total_list.by_id_list(music_id_list)
        
        # 按定数分组
        all_level_dict = {}
        for lv in list(reversed(levelList)):
            all_level_dict[lv] = []
        
        for m in music:
            # 如果是 ReMASTER 曲目，使用第5个难度（索引4）
            if m.id in remaster_id_list and len(m.level) > 4:
                all_level_dict[m.level[4]].append(m)
            else:
                all_level_dict[m.level[3]].append(m)
        
        # 分页：13+ 及以上为第1页，13 及以下为第2页
        keys = [k for k in all_level_dict.keys() if all_level_dict[k]]
        
        if '13' in keys:
            idx = keys.index('13')
            lv_13_plus = {k: all_level_dict[k] for k in keys[:idx]}  # 13+ 及以上
            lv_13_low = {k: all_level_dict[k] for k in keys[idx:]}   # 13 及以下
        else:
            lv_13_plus = all_level_dict
            lv_13_low = {}
        
        sbi = ScoreBaseImage if maiconfig.saveinmem else ScoreBaseImage()
        from .maimaidx_theme import Theme as _Theme, resolve_theme_path as _rtp
        _t = _Theme.get_default().value
        
        # 生成两页
        for page_num, level_dict in enumerate([lv_13_plus, lv_13_low], start=1):
            if not any(level_dict.values()):
                continue
            
            # 计算高度
            lines = 0
            interval = 0
            for lv in level_dict:
                musicnum = len(level_dict[lv])
                if musicnum == 0:
                    continue
                interval += 1
                remainder = musicnum % 12
                lines += (musicnum // 12) + (1 if remainder else 0)
            
            # 与 beta 一致：GRID_STEP=96, 等级间距 30
            linesheight = 96 * lines + interval * 30
            width, height = 1400, 490 + linesheight + 180
            
            im = tricolor_gradient(width, height)
            
            im.alpha_composite(sbi.aurora_bg)
            im.alpha_composite(sbi.shines_bg, (34, 0))
            im.alpha_composite(sbi.rainbow_bg, (319, height - 643))
            im.alpha_composite(sbi.rainbow_bottom_bg, (100, height - 343))
            for h in range((height // 358) + 1):
                im.alpha_composite(sbi.pattern_bg, (0, (358 + 7) * h))
            
            dr = ImageDraw.Draw(im)
            ts = DrawText(dr, TBFONT)
            sy = DrawText(dr, SIYUAN)
            _des = _rtp(maimaidir, _t, 'design.png')
            if _des.exists():
                im.alpha_composite(Image.open(_des), (200, height - 113))
            
            # 页码标识
            sy.draw(700, height - 140, 30, f'Pages {page_num}/2', sbi.text_color, 'mm')
            sy.draw(
                700, 
                height - 70, 
                22, 
                f'Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {maiconfig.botName} BOT', 
                sbi.text_color, 
                'mm'
            )
            
            id_bg = Image.new('RGBA', (110, 20), (124, 129, 255, 255))
            
            # === 曲绘网格：与 beta 一致 ===
            GRID_STEP = 96
            START_X = 180
            START_Y = 490
            ROW_COUNT = 12
            
            current_y = START_Y
            for r in level_dict:
                # 按定数排序（ReMASTER 使用索引4，其他使用索引3）
                level_dict[r].sort(key=lambda x: x.ds[4] if x.id in remaster_id_list and len(x.ds) > 4 else x.ds[3], reverse=True)
                
                songs = level_dict[r]
                if not songs:
                    continue
                
                # 等级标签
                ts.draw(72, current_y + 40, 40, r, sbi.text_color, 'lm', 4, (255, 255, 255, 255))
                
                max_row = 0
                for num, music in enumerate(songs):
                    row, col = divmod(num, ROW_COUNT)
                    max_row = max(max_row, row)
                    x = START_X + col * GRID_STEP
                    y_pos = current_y + row * GRID_STEP
                    cover = music_picture(music.id)
                    im.alpha_composite(Image.open(cover).resize((80, 80)), (x, y_pos))
                    im.alpha_composite(id_bg, (x - 5, y_pos - 5))
                    ts.draw(x + 56, y_pos + 4, 16, music.id, anchor='mm')
                current_y += (max_row + 1) * GRID_STEP + 30
            
            # 保存
            by = BytesIO()
            im.save(by, 'PNG')
            async with aiofiles.open(plate_tabledir / f'舞-{page_num}.png', 'wb') as f:
                await f.write(by.getbuffer())
            log.info(f'舞-{page_num} 完成表更新完成')
        
        return '舞/霸者完成表更新完成'
    except Exception as e:
        log.error(traceback.format_exc())
        return f'舞/霸者完成表更新失败，Error: {e}'


async def update_plate_table() -> str:
    """更新完成表"""
    try:
        plate_tabledir.mkdir(parents=True, exist_ok=True)
        version = list(_ for _ in plate_to_dx_version.keys())[1:]
        # version.append('霸')
        # version.append('舞')
        id_bg = Image.new('RGBA', (100, 20), (124, 129, 255, 255))
        rlv: Dict[str, List[Music]] = {}
        for _ in list(reversed(levelList)):
            rlv[_] = []
        sbi = ScoreBaseImage if maiconfig.saveinmem else ScoreBaseImage()
        from .maimaidx_theme import Theme as _Theme, resolve_theme_path as _rtp
        _t = _Theme.get_default().value
        for _v in version:
            if _v in platecn:
                _v = platecn[_v]
            ver, _ver = version_map.get(_v, ([plate_to_dx_version.get(_v)], _v))
            
            music_id_list = mai.total_plate_id_list[_ver]
            music = mai.total_list.by_id_list(music_id_list)
            ralv = copy.deepcopy(rlv)

            for m in music:
                ralv[m.level[3]].append(m)

            lines = 0
            interval = 0
            for _ in ralv:
                musicnum = len(ralv[_])
                if musicnum == 0:
                    continue
                interval += 1
                remainder = musicnum % 12
                lines += (musicnum // 12) + (1 if remainder else 0)
            
            # 与 beta 一致：GRID_STEP=96, 等级间距 30
            linesheight = 96 * lines + interval * 30
            """
            `linesheight`: 各等级曲绘和间隔总和高度
            """
            width, height = 1400, 490 + linesheight + 180
            """
            `150` 为底部图片 `design` 高度 + 上下间隔高度
            `linesheight` 为各等级曲绘和间隔总和高度
            `360` 为顶部图片 `` 高度 + 上下间隔高度
            """

            im = tricolor_gradient(width, height)
            
            im.alpha_composite(sbi.aurora_bg)
            im.alpha_composite(sbi.shines_bg, (34, 0))
            im.alpha_composite(sbi.rainbow_bg, (319, height - 643))
            im.alpha_composite(sbi.rainbow_bottom_bg, (100, height - 343))
            for h in range((height // 358) + 1):
                im.alpha_composite(sbi.pattern_bg, (0, (358 + 7) * h))
            
            dr = ImageDraw.Draw(im)
            ts = DrawText(dr, TBFONT)
            sy = DrawText(dr, SIYUAN)
            _des = _rtp(maimaidir, _t, 'design.png')
            if _des.exists():
                im.alpha_composite(Image.open(_des), (200, height - 113))
            sy.draw(
                700, 
                height - 70, 
                22, 
                f'Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {maiconfig.botName} BOT', 
                sbi.text_color, 
                'mm'
            )
            y = 245
            id_bg = Image.new('RGBA', (110, 20), (124, 129, 255, 255))
            
            # === 曲绘网格：与 beta 一致 ===
            GRID_STEP = 96
            START_X = 180
            START_Y = 490
            ROW_COUNT = 12
            
            current_y = START_Y
            for r in ralv:
                if _v in ['霸', '舞']:
                    ralv[r].sort(key=lambda x: x.ds[-1], reverse=True)
                else:
                    ralv[r].sort(key=lambda x: x.ds[3], reverse=True)
                
                songs = ralv[r]
                if not songs:
                    continue
                
                # 等级标签
                ts.draw(72, current_y + 40, 40, r, sbi.text_color, 'lm', 4, (255, 255, 255, 255))
                
                max_row = 0
                for num, music in enumerate(songs):
                    row, col = divmod(num, ROW_COUNT)
                    max_row = max(max_row, row)
                    x = START_X + col * GRID_STEP
                    y_pos = current_y + row * GRID_STEP
                    cover = music_picture(music.id)
                    im.alpha_composite(Image.open(cover).resize((80, 80)), (x, y_pos))
                    im.alpha_composite(id_bg, (x - 5, y_pos - 5))
                    ts.draw(x + 56, y_pos + 4, 16, music.id, anchor='mm')
                current_y += (max_row + 1) * GRID_STEP + 30

            by = BytesIO()
            im.save(by, 'PNG')
            async with aiofiles.open(plate_tabledir / f'{_v}.png', 'wb') as f:
                await f.write(by.getbuffer())
            log.info(f'{_v}代牌子更新完成')
        
        # 更新舞/霸者完成表
        wu_result = await update_wu_plate_table()
        log.info(wu_result)
        
        return f'完成表更新完成'
    except Exception as e:
        log.error(traceback.format_exc())
        return f'完成表更新失败，Error: {e}'